In [1]:

from item_functions import generate_items_from_schedule
from itertools import combinations
from student import *
from student2 import *
from conflict_matrix import *

In [2]:
#items = generate_items_from_schedule('Fall 2023 Schedule-2.xlsx')
items = generate_items_from_schedule('fall2023schedule.xlsx')
student = Student(items)

val_map = student.course_value_map
print(val_map)

{'Hardware': [[()], [('COMPSCI335',)]], 'Social': [[()], [('CICS305',), ('COMPSCI328',), ('COMPSCI420',), ('COMPSCI429',), ('INFO324',)], [('CICS305', 'COMPSCI328'), ('CICS305', 'COMPSCI420'), ('CICS305', 'COMPSCI429'), ('CICS305', 'INFO324'), ('COMPSCI328', 'COMPSCI420'), ('COMPSCI328', 'COMPSCI429'), ('COMPSCI420', 'COMPSCI429'), ('COMPSCI328', 'INFO324'), ('COMPSCI420', 'INFO324'), ('COMPSCI429', 'INFO324')], [('CICS305', 'COMPSCI328', 'COMPSCI420'), ('CICS305', 'COMPSCI328', 'COMPSCI429'), ('CICS305', 'COMPSCI420', 'COMPSCI429'), ('CICS305', 'COMPSCI328', 'INFO324'), ('CICS305', 'COMPSCI420', 'INFO324'), ('CICS305', 'COMPSCI429', 'INFO324'), ('COMPSCI328', 'COMPSCI420', 'COMPSCI429'), ('COMPSCI328', 'COMPSCI420', 'INFO324'), ('COMPSCI328', 'COMPSCI429', 'INFO324'), ('COMPSCI420', 'COMPSCI429', 'INFO324')], [('CICS305', 'COMPSCI328', 'COMPSCI420', 'COMPSCI429'), ('CICS305', 'COMPSCI328', 'COMPSCI420', 'INFO324'), ('CICS305', 'COMPSCI328', 'COMPSCI429', 'INFO324'), ('CICS305', 'COMPS

In [9]:
print(student.cat_vals)

defaultdict(<function Student.__init__.<locals>.def_value at 0x7faf30c7cd30>, {'Social': [[0], [1, 1, 1, 0, 0], [1, 1, 1, 1, 2, 0, 0, 2, 0, 2], [3, 0, 2, 0, 1, 3, 1, 0, 0, 2], [2, 0, 2, 3, 4]], 'Programming': [[0], [1, 0, 0, 1, 1], [2, 1, 0, 2, 2, 0, 0, 0, 2, 0], [2, 3, 1, 0, 2, 1, 3, 2, 1, 3], [2, 1, 0, 3, 4]]})


In [10]:
bundle = [items[24], items[21], items[0], items[3], items[28], items[29]]
val = student.valuation(bundle)
print(val)

3


In [18]:
import datetime

time = '04:00 pM - 05:15 pM'
time2 = '03:00 aM - 04:15 aM'

times = [datetime.datetime.strptime(item, "%I:%M %p") for item in time.split(" - ")]
times2 = [datetime.datetime.strptime(item, "%I:%M %p") for item in time2.split(" - ")]

if (times[1] > times2[0] and times[1] < times2[1]) or (times2[1] > times[0] and times2[1] < times[1]):
    print(True)

x = [(1,2),(3,4)]
print(x[0][1])

2


In [17]:
from agent_functions import Agent, gen_random_agents
from item_functions import generate_items_from_schedule
from allocation_functions import yankee_swap, SPIRE_algorithm, round_robin
from metric_functions import utilitarian_welfare, nash_welfare, EF, EF_1, EF_X
import matplotlib.pyplot as plt
import random
import numpy as np

s1 = Student(items)
s2 = Student(items)
s3 = Student(items)
s4 = Student(items)
s5 = Student(items)

students = [s1, s2, s3, s4, s5]

X=yankee_swap(students, items, plot_exchange_graph=False)
print('Yankee Swap Allocation')
print(X)

Initial allocation:
[[ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 17   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [ 45   0   0   0   0   0]
 [ 45   0   0   0   0   0]
 [ 45   0   0   0   0   0]
 [ 20   0   0   0   0   0]
 [ 80   0   0   0   0   0]
 [ 87   0   0   0   0   0]
 [ 41   0   0   0   0   0]
 [ 55   0   0   0   0   0]
 [ 84   0   0   0   0   0]
 [ 84   0   0   0   0   0]
 [ 70   0   0   0   0   0]
 [ 80   0   0   0   0   0]
 [120   0   0   0   0   0]
 [180   0   0   0   0   0]
 [220   0   0   0   0   0]
 [ 40   0   0   0   0   0]
 [  5   

In [22]:
print('Utilitatian: ',utilitarian_welfare(X,students,items))
print('Nash: ',nash_welfare(X, students,items))
print('EF: ',EF(X, students,items))
print('EF_1: ',EF_1(X, students,items))
print('EF_X: ',EF_X(X, students,items))
# X=round_robin(students,items)
# print('Round Robin Allocation')
# print(X)
# print('Utilitatian: ',utilitarian_welfare(X,students,items))
# print('Nash: ',nash_welfare(X, students,items))
# print('EF: ',EF(X, students,items))
# print('EF_1: ',EF_1(X, students,items))
# print('EF_X: ',EF_X(X, students,items))
X=SPIRE_algorithm(students,items)
print(X)
print('SPIRE Allocation')
print('Utilitatian: ',utilitarian_welfare(X,students,items))
print('Nash: ',nash_welfare(X, students,items))
print('EF: ',EF(X, students,items))
print('EF_1: ',EF_1(X, students,items))
print('EF_X: ',EF_X(X, students,items))

Utilitatian:  4.0
Nash:  (0, 3.629678089903706)
EF:  0
EF_1:  0
EF_X:  0


AttributeError: 'Student' object has no attribute 'get_desired_items_indexes'

In [5]:
student2 = Student2(items)

print(student2.alloc_mat)
print(student2.constraints)
print(student2.pref_mat)
print(student2.pref_mat.dot(student2.alloc_mat))

['Cybersec', 'Data Science', 'Hardware', 'Programming']
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [4.]
 [4.]
 [4.]
 [4.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [6.]]
[[1. 1. 1. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [3]:
from agent_functions import Agent, gen_random_agents
from item_functions import generate_items_from_schedule
from allocation_functions import yankee_swap, SPIRE_algorithm, round_robin
from metric_functions import utilitarian_welfare, nash_welfare, EF, EF_1, EF_X
import matplotlib.pyplot as plt
import random
import numpy as np

conflicts, constraints = gen_conflict_matrix(items)

s1 = Student2(items, conflicts, constraints); s2 = Student2(items, conflicts, constraints)
s3 = Student2(items, conflicts, constraints); s4 = Student2(items, conflicts, constraints)
s5 = Student2(items, conflicts, constraints); s6 = Student2(items, conflicts, constraints)
s7 = Student2(items, conflicts, constraints); s8 = Student2(items, conflicts, constraints)
s9 = Student2(items, conflicts, constraints); s10 = Student2(items, conflicts, constraints)
s11 = Student2(items, conflicts, constraints); s12 = Student2(items, conflicts, constraints)
s13 = Student2(items, conflicts, constraints); s14 = Student2(items, conflicts, constraints)
s15 = Student2(items, conflicts, constraints); s16 = Student2(items, conflicts, constraints)
s17 = Student2(items, conflicts, constraints); s18 = Student2(items, conflicts, constraints)
s19 = Student2(items, conflicts, constraints); s20 = Student2(items, conflicts, constraints)
s21 = Student2(items, conflicts, constraints); s22 = Student2(items, conflicts, constraints)
s23 = Student2(items, conflicts, constraints); s24 = Student2(items, conflicts, constraints)
s25 = Student2(items, conflicts, constraints); s26 = Student2(items, conflicts, constraints)
s27 = Student2(items, conflicts, constraints); s28 = Student2(items, conflicts, constraints)
s29 = Student2(items, conflicts, constraints); s30 = Student2(items, conflicts, constraints)
s31 = Student2(items, conflicts, constraints); s32 = Student2(items, conflicts, constraints)
s33 = Student2(items, conflicts, constraints); s34 = Student2(items, conflicts, constraints)
s35 = Student2(items, conflicts, constraints); s36 = Student2(items, conflicts, constraints)
s37 = Student2(items, conflicts, constraints); s38 = Student2(items, conflicts, constraints)
s39 = Student2(items, conflicts, constraints); s40 = Student2(items, conflicts, constraints)
s41 = Student2(items, conflicts, constraints); s42 = Student2(items, conflicts, constraints)
s43 = Student2(items, conflicts, constraints); s44 = Student2(items, conflicts, constraints)
s45 = Student2(items, conflicts, constraints); s46 = Student2(items, conflicts, constraints)
s47 = Student2(items, conflicts, constraints); s48 = Student2(items, conflicts, constraints)
s49 = Student2(items, conflicts, constraints); s50 = Student2(items, conflicts, constraints)
s51 = Student2(items, conflicts, constraints); s52 = Student2(items, conflicts, constraints)
s53 = Student2(items, conflicts, constraints); s54 = Student2(items, conflicts, constraints)
s55 = Student2(items, conflicts, constraints); s56 = Student2(items, conflicts, constraints)
s57 = Student2(items, conflicts, constraints); s58 = Student2(items, conflicts, constraints)
s59 = Student2(items, conflicts, constraints); s60 = Student2(items, conflicts, constraints)
s61 = Student2(items, conflicts, constraints); s62 = Student2(items, conflicts, constraints)
s63 = Student2(items, conflicts, constraints); s64 = Student2(items, conflicts, constraints)
s65 = Student2(items, conflicts, constraints); s66 = Student2(items, conflicts, constraints)
s67 = Student2(items, conflicts, constraints); s68 = Student2(items, conflicts, constraints)
s69 = Student2(items, conflicts, constraints); s70 = Student2(items, conflicts, constraints)
s71 = Student2(items, conflicts, constraints); s72 = Student2(items, conflicts, constraints)
s73 = Student2(items, conflicts, constraints); s74 = Student2(items, conflicts, constraints)
s75 = Student2(items, conflicts, constraints); s76 = Student2(items, conflicts, constraints)
s77 = Student2(items, conflicts, constraints); s78 = Student2(items, conflicts, constraints)
s79 = Student2(items, conflicts, constraints); s80 = Student2(items, conflicts, constraints)
s81 = Student2(items, conflicts, constraints); s82 = Student2(items, conflicts, constraints)
s83 = Student2(items, conflicts, constraints); s84 = Student2(items, conflicts, constraints)
s85 = Student2(items, conflicts, constraints); s86 = Student2(items, conflicts, constraints)
s87 = Student2(items, conflicts, constraints); s88 = Student2(items, conflicts, constraints)
s89 = Student2(items, conflicts, constraints); s90 = Student2(items, conflicts, constraints)
s91 = Student2(items, conflicts, constraints); s92 = Student2(items, conflicts, constraints)
s93 = Student2(items, conflicts, constraints); s94 = Student2(items, conflicts, constraints)
s95 = Student2(items, conflicts, constraints); s96 = Student2(items, conflicts, constraints)
s97 = Student2(items, conflicts, constraints); s98 = Student2(items, conflicts, constraints)
s99 = Student2(items, conflicts, constraints); s100 = Student2(items, conflicts, constraints)

students = [s1, s2, s3, s4, s5, s6, s7, s8, s9, s10,
            s11, s12, s13, s14, s15, s16, s17, s18, s19, s20,
            s21, s22, s23, s24, s25, s26, s27, s28, s29, s30,
            s31, s32, s33, s34, s35, s36, s37, s38, s39, s40,
            s41, s42, s43, s44, s45, s46, s47, s48, s49, s50,
            s51, s52, s53, s54, s55, s56, s57, s58, s59, s60,
            s61, s62, s63, s64, s65, s66, s67, s68, s69, s70,
            s71, s72, s73, s74, s75, s76, s77, s78, s79, s80,
            s81, s82, s83, s84, s85, s86, s87, s88, s89, s90,
            s91, s92, s93, s94, s95, s96, s97, s98, s99, s100,]

X=yankee_swap(students, items, plot_exchange_graph=False)
print('Yankee Swap Allocation')
print(X)
print('Utilitatian: ',utilitarian_welfare(X,students,items))
print('Nash: ',nash_welfare(X, students,items))
print('EF: ',EF(X, students,items))
print('EF_1: ',EF_1(X, students,items))
print('EF_X: ',EF_X(X, students,items))

['Programming', 'Cybersec', 'Data Science']
['Programming', 'Math', 'Cybersec', 'Hardware']
['Math']
['Social']
['Programming', 'Cybersec', 'Hardware']
['Hardware']
['Data Science', 'Cybersec', 'Math', 'Systems']
['Social', 'Math', 'Hardware']
['Data Science']
['Data Science', 'Systems', 'Math']
['Math', 'Data Science', 'Hardware']
['Math', 'Systems', 'Cybersec', 'Hardware']
['Data Science']
['Cybersec', 'Math', 'Social', 'Programming']
['Programming', 'Math', 'Hardware', 'Social']
['Systems']
['Social', 'Programming']
['Social', 'Systems', 'Math']
['Social']
['Social', 'Math', 'Systems', 'Cybersec']
['Data Science']
['Math', 'Systems']
['Hardware', 'Cybersec', 'Math']
['Programming', 'Data Science']
['Hardware', 'Social', 'Cybersec', 'Data Science']
['Social', 'Data Science']
['Social', 'Systems']
['Math', 'Social']
['Data Science', 'Hardware']
['Programming']
['Hardware']
['Programming', 'Hardware', 'Systems', 'Cybersec']
['Systems']
['Math', 'Social']
['Programming', 'Cybersec']
['S

In [6]:
X=round_robin(students,items)
print('Round Robin Allocation')
print(X)
print('Utilitatian: ',utilitarian_welfare(X,students,items))
print('Nash: ',nash_welfare(X, students,items))
print('EF: ',EF(X, students,items))
print('EF_1: ',EF_1(X, students,items))
print('EF_X: ',EF_X(X, students,items))
# X=SPIRE_algorithm(students,items)
# print(X)
# print('SPIRE Allocation')
# print('Utilitatian: ',utilitarian_welfare(X,students,items))
# print('Nash: ',nash_welfare(X, students,items))
# print('EF: ',EF(X, students,items))
# print('EF_1: ',EF_1(X, students,items))
# print('EF_X: ',EF_X(X, students,items))

AttributeError: 'Student2' object has no attribute 'get_desired_items_indexes'